[ERROR][models.go:39]2019/12/04 14:59:42 [dial tcp: lookup tcp/数据库端口号: Servname not supported for ai_socktype]
[INFO][main.go:22]2019/12/04 14:59:42 [Actual pid is %d 32091]
[INFO][main.go:26]2019/12/04 15:00:41 [Server err: %v accept tcp [::]:8080: use of closed network connection]
[ERROR][models.go:39]2019/12/04 15:00:42 [dial tcp: lookup tcp/数据库端口号: Servname not supported for ai_socktype]
[INFO][main.go:22]2019/12/04 15:00:42 [Actual pid is %d 32302]
[INFO][main.go:26]2019/12/04 15:01:19 [Server err: %v accept tcp [::]:8080: use of closed network connection]
[ERROR][models.go:39]2019/12/04 15:01:21 [dial tcp: lookup tcp/数据库端口号: Servname not supported for ai_socktype]
[INFO][main.go:22]2019/12/04 15:01:21 [Actual pid is %d 32614]
[INFO][main.go:26]2019/12/04 15:02:28 [Server err: %v accept tcp [::]:8080: use of closed network connection]
[ERROR][models.go:39]2019/12/04 15:02:29 [dial tcp: lookup tcp/数据库端口号: Servname not supported for ai_socktype]
[INFO][main.go:22]2019/12/04 15:02:29 [Actual pid is %d 358]
[INFO][main.go:26]2019/12/04 15:03:42 [Server err: %v accept tcp [::]:8080: use of closed network connection]
[ERROR][models.go:39]2019/12/04 15:03:44 [dial tcp: lookup tcp/数据库端口号: Servname not supported for ai_socktype]
[INFO][main.go:22]2019/12/04 15:03:44 [Actual pid is %d 635]
[INFO][main.go:26]2019/12/04 15:03:56 [Server err: %v accept tcp [::]:8080: use of closed network connection]
[ERROR][models.go:39]2019/12/04 15:03:58 [dial tcp: lookup tcp/数据库端口号: Servname not supported for ai_socktype]
[INFO][main.go:22]2019/12/04 15:03:58 [Actual pid is %d 871]
[INFO][main.go:26]2019/12/04 15:06:10 [Server err: %v accept tcp [::]:8080: use of closed network connection]
[ERROR][models.go:39]2019/12/04 15:06:12 [dial tcp: lookup tcp/数据库端口号: Servname not supported for ai_socktype]
[INFO][main.go:22]2019/12/04 15:06:12 [Actual pid is %d 1165]
[INFO][main.go:26]2019/12/04 15:06:38 [Server err: %v accept tcp [::]:8080: use of closed network connection]
[ERROR][models.go:39]2019/12/04 15:06:45 [dial tcp: lookup tcp/数据库端口号: Servname not supported for ai_socktype]
[INFO][main.go:22]2019/12/04 15:06:45 [Actual pid is %d 3854]
[INFO][auth.go:45]2019/12/04 15:07:59 [Username.Required Can not be empty]
[INFO][auth.go:45]2019/12/04 15:07:59 [Password.Required Can not be empty]
[ERROR][models.go:39]2019/12/04 15:09:23 [dial tcp: lookup tcp/数据库端口号: Servname not supported for ai_socktype]
[INFO][main.go:22]2019/12/04 15:09:23 [Actual pid is %d 4159]
[INFO][main.go:26]2019/12/04 15:11:12 [Server err: %v accept tcp [::]:8080: use of closed network connection]
[ERROR][models.go:39]2019/12/04 15:11:14 [dial tcp: lookup tcp/数据库端口号: Servname not supported for ai_socktype]
[INFO][main.go:22]2019/12/04 15:11:14 [Actual pid is %d 4623]
[INFO][main.go:26]2019/12/04 15:15:59 [Server err: %v accept tcp [::]:8080: use of closed network connection]
[ERROR][models.go:39]2019/12/04 15:16:00 [dial tcp: lookup tcp/数据库端口号: Servname not supported for ai_socktype]
[INFO][main.go:22]2019/12/04 15:16:00 [Actual pid is %d 4983]
[INFO][main.go:26]2019/12/04 15:19:10 [Server err: %v accept tcp [::]:8080: use of closed network connection]
[ERROR][models.go:39]2019/12/04 16:53:29 [dial tcp: lookup tcp/数据库端口号: Servname not supported for ai_socktype]
[INFO][main.go:22]2019/12/04 16:53:29 [Actual pid is %d 14182]
[INFO][main.go:26]2019/12/04 16:55:46 [Server err: %v accept tcp [::]:8080: use of closed network connection]
[ERROR][models.go:39]2019/12/04 16:55:47 [dial tcp: lookup tcp/数据库端口号: Servname not supported for ai_socktype]
[INFO][main.go:22]2019/12/04 16:55:47 [Actual pid is %d 14577]
[INFO][main.go:26]2019/12/04 19:50:18 [Server err: %v accept tcp [::]:8080: use of closed network connection]
[INFO][main.go:22]2019/12/04 19:50:20 [Actual pid is %d 24711]
[INFO][main.go:26]2019/12/04 19:57:53 [Server err: %v accept tcp [::]:8080: use of closed network connection]
[ERROR][models.go:39]2019/12/04 19:57:55 [Error 1049: Unknown database 'user']
[INFO][main.go:22]2019/12/04 19:57:55 [Actual pid is %d 25307]
[INFO][main.go:26]2019/12/04 19:59:42 [Server err: %v accept tcp [::]:8080: use of closed network connection]
[ERROR][models.go:39]2019/12/04 19:59:43 [Error 1049: Unknown database 'user']
[INFO][main.go:22]2019/12/04 19:59:43 [Actual pid is %d 25557]
[INFO][main.go:26]2019/12/04 20:01:49 [Server err: %v accept tcp [::]:8080: use of closed network connection]
[ERROR][models.go:39]2019/12/04 20:01:51 [Error 1049: Unknown database 'user']
[INFO][main.go:22]2019/12/04 20:01:51 [Actual pid is %d 25809]
[INFO][main.go:26]2019/12/04 20:03:07 [Server err: %v accept tcp [::]:8080: use of closed network connection]
[ERROR][models.go:39]2019/12/04 20:03:09 [Error 1049: Unknown database 'user']
[INFO][main.go:22]2019/12/04 20:03:09 [Actual pid is %d 26081]
[ERROR][models.go:39]2019/12/04 20:03:42 [Error 1049: Unknown database 'user']
[INFO][main.go:22]2019/12/04 20:03:42 [Actual pid is %d 26249]
[INFO][main.go:26]2019/12/04 20:05:57 [Server err: %v accept tcp [::]:8080: use of closed network connection]
[ERROR][models.go:39]2019/12/04 20:05:58 [Error 1049: Unknown database 'user']
[INFO][main.go:22]2019/12/04 20:05:58 [Actual pid is %d 26543]
[INFO][main.go:26]2019/12/04 20:14:43 [Server err: %v accept tcp [::]:8080: use of closed network connection]
[ERROR][models.go:39]2019/12/04 20:14:45 [Error 1049: Unknown database 'user']
[INFO][main.go:23]2019/12/04 20:14:52 [Actual pid is %d 27048]
[ERROR][models.go:39]2019/12/04 20:15:45 [Error 1049: Unknown database 'user']
[INFO][main.go:23]2019/12/04 20:15:45 [Actual pid is %d 27242]
[INFO][main.go:27]2019/12/04 20:17:48 [Server err: %v accept tcp [::]:8080: use of closed network connection]
[ERROR][models.go:39]2019/12/04 20:17:50 [Error 1049: Unknown database 'user']
[INFO][main.go:23]2019/12/04 20:17:50 [Actual pid is %d 27443]
[ERROR][models.go:39]2019/12/04 20:20:42 [Error 1049: Unknown database 'test.user']
[INFO][main.go:23]2019/12/04 20:20:42 [Actual pid is %d 27755]
